version: "3"
services:
  web:
    build: ./Project_Job
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Project_Job/:/usr/src/Project_Job/
    ports:
        - '8000:8000'
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Job
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=django_db

volumes:
  postgres_volume:
